version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - VITE_FRONTEND_URL=http://173.212.254.228:3001
      - VITE_API_URL=http://173.212.254.228:5000
      - VITE_API_BASE_PATH=/api/v1
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 