version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=http://173.212.254.228:5000
      - VITE_API_BASE_PATH=/api/v1 